[font]
size = 13.0

[font.bold]
family = "CaskaydiaCoveNerdFont"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCoveNerdFont"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCoveNerdFont"
style = "Italic"

[font.normal]
family = "CaskaydiaCoveNerdFont"
style = "Regular"

[env]
TERM = "xterm-256color"
[selection]
save_to_clipboard = true
